!!python/object:huggingface_hub.community.DiscussionWithDetails
author: Giselle
conflicting_files: null
created_at: 2023-01-10 12:37:31+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/881b6150bf0210615cc94fd0bba9dce2.svg
      fullname: Giselle de Farias Rosa
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: Giselle
      type: user
    createdAt: '2023-01-10T12:37:31.000Z'
    data:
      edited: false
      editors:
      - Giselle
      hidden: false
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/881b6150bf0210615cc94fd0bba9dce2.svg
          fullname: Giselle de Farias Rosa
          isHf: false
          isPro: false
          name: Giselle
          type: user
        html: '<p>I''m getting this error when trying to use the API for en_scibert_ScienceIE
          NER:<br>"cannot import name ''DatasetInfo'' from ''huggingface_hub.hf_api''
          (/usr/local/lib/python3.8/site-packages/huggingface_hub/hf_api.py)".<br>How
          to solve this?</p>

          '
        raw: "I'm getting this error when trying to use the API for en_scibert_ScienceIE\
          \ NER: \r\n\"cannot import name 'DatasetInfo' from 'huggingface_hub.hf_api'\
          \ (/usr/local/lib/python3.8/site-packages/huggingface_hub/hf_api.py)\".\r\
          \nHow to solve this?\r\n\r\n"
        updatedAt: '2023-01-10T12:37:31.707Z'
      numEdits: 0
      reactions: []
    id: 63bd5c0bb3b8c44f8ce031ee
    type: comment
  author: Giselle
  content: "I'm getting this error when trying to use the API for en_scibert_ScienceIE\
    \ NER: \r\n\"cannot import name 'DatasetInfo' from 'huggingface_hub.hf_api' (/usr/local/lib/python3.8/site-packages/huggingface_hub/hf_api.py)\"\
    .\r\nHow to solve this?\r\n\r\n"
  created_at: 2023-01-10 12:37:31+00:00
  edited: false
  hidden: false
  id: 63bd5c0bb3b8c44f8ce031ee
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 1
repo_id: UBIAI/en_scibert_ScienceIE
repo_type: model
status: open
target_branch: null
title: Error while using the API
