!!python/object:huggingface_hub.community.DiscussionWithDetails
author: interstellarninja
conflicting_files: null
created_at: 2023-05-18 03:39:47+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/6446be9a15a27291ef8bea10/9_gywXgzL9Jk3MYLdX9RG.jpeg?w=200&h=200&f=face
      fullname: interstellarninja
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: interstellarninja
      type: user
    createdAt: '2023-05-18T04:39:47.000Z'
    data:
      edited: false
      editors:
      - interstellarninja
      hidden: false
      isReport: false
      latest:
        author:
          avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/6446be9a15a27291ef8bea10/9_gywXgzL9Jk3MYLdX9RG.jpeg?w=200&h=200&f=face
          fullname: interstellarninja
          isHf: false
          isPro: false
          name: interstellarninja
          type: user
        html: "<p>I'm getting the error when I run this line:<br>gpt = GPTJForCausalLM.from_pretrained(\"\
          hivemind/gpt-j-6B-8bit\", low_cpu_mem_usage=True)</p>\n<p>/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py:2608\
          \ in from_pretrained   \u2502<br>\u2502                                \
          \                                                                  \u2502\
          <br>\u2502   2605 \u2502   \u2502                                      \
          \                                               \u2502<br>\u2502   2606\
          \ \u2502   \u2502   # Instantiate model.                               \
          \                               \u2502<br>\u2502   2607 \u2502   \u2502\
          \   init_contexts = [no_init_weights(_enable=_fast_init)]              \
          \               \u2502<br>\u2502 \u2771 2608 \u2502   \u2502           \
          \                                                                      \
          \    \u2502<br>\u2502   2609 \u2502   \u2502   if is_deepspeed_zero3_enabled():\
          \                                                  \u2502<br>\u2502   2610\
          \ \u2502   \u2502   \u2502   import deepspeed                          \
          \                                    \u2502<br>\u2502   2611           \
          \                        </p>\n"
        raw: "I'm getting the error when I run this line:\r\ngpt = GPTJForCausalLM.from_pretrained(\"\
          hivemind/gpt-j-6B-8bit\", low_cpu_mem_usage=True)\r\n\r\n/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py:2608\
          \ in from_pretrained   \u2502\r\n\u2502                                \
          \                                                                  \u2502\
          \r\n\u2502   2605 \u2502   \u2502                                      \
          \                                               \u2502\r\n\u2502   2606\
          \ \u2502   \u2502   # Instantiate model.                               \
          \                               \u2502\r\n\u2502   2607 \u2502   \u2502\
          \   init_contexts = [no_init_weights(_enable=_fast_init)]              \
          \               \u2502\r\n\u2502 \u2771 2608 \u2502   \u2502           \
          \                                                                      \
          \    \u2502\r\n\u2502   2609 \u2502   \u2502   if is_deepspeed_zero3_enabled():\
          \                                                  \u2502\r\n\u2502   2610\
          \ \u2502   \u2502   \u2502   import deepspeed                          \
          \                                    \u2502\r\n\u2502   2611           \
          \                        "
        updatedAt: '2023-05-18T04:39:47.077Z'
      numEdits: 0
      reactions: []
    id: 6465ac130e6c7618f615db67
    type: comment
  author: interstellarninja
  content: "I'm getting the error when I run this line:\r\ngpt = GPTJForCausalLM.from_pretrained(\"\
    hivemind/gpt-j-6B-8bit\", low_cpu_mem_usage=True)\r\n\r\n/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py:2608\
    \ in from_pretrained   \u2502\r\n\u2502                                      \
    \                                                            \u2502\r\n\u2502\
    \   2605 \u2502   \u2502                                                     \
    \                                \u2502\r\n\u2502   2606 \u2502   \u2502   # Instantiate\
    \ model.                                                              \u2502\r\
    \n\u2502   2607 \u2502   \u2502   init_contexts = [no_init_weights(_enable=_fast_init)]\
    \                             \u2502\r\n\u2502 \u2771 2608 \u2502   \u2502   \
    \                                                                            \
    \      \u2502\r\n\u2502   2609 \u2502   \u2502   if is_deepspeed_zero3_enabled():\
    \                                                  \u2502\r\n\u2502   2610 \u2502\
    \   \u2502   \u2502   import deepspeed                                       \
    \                       \u2502\r\n\u2502   2611                              \
    \     "
  created_at: 2023-05-18 03:39:47+00:00
  edited: false
  hidden: false
  id: 6465ac130e6c7618f615db67
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 16
repo_id: hivemind/gpt-j-6B-8bit
repo_type: model
status: open
target_branch: null
title: 'NameError: name ''init_empty_weights'' is not defined'
