!!python/object:huggingface_hub.community.DiscussionWithDetails
author: lazyDataScientist
conflicting_files: null
created_at: 2024-01-19 16:59:29+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/633a39ec8f27255b6b571101/7J_BcRm7ua0WZNIGwEzlo.png?w=200&h=200&f=face
      fullname: Cedrick Hesketh
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: lazyDataScientist
      type: user
    createdAt: '2024-01-19T16:59:29.000Z'
    data:
      edited: true
      editors:
      - lazyDataScientist
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.7334691882133484
      isReport: false
      latest:
        author:
          avatarUrl: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/633a39ec8f27255b6b571101/7J_BcRm7ua0WZNIGwEzlo.png?w=200&h=200&f=face
          fullname: Cedrick Hesketh
          isHf: false
          isPro: false
          name: lazyDataScientist
          type: user
        html: '<p>Getting <code>ValueError: OC is not a multiple of cta_N = 64</code>
          at the line <code>out = awq_inference_engine.gemm_forward_cuda(x.reshape(-1,
          x.shape[-1]), self.qweight, self.scales, self.qzeroes, 8)</code> in the
          <code>linear.py</code> file from the <code>AutoAWQ</code> package. I am
          getting this error when loading the model in using Transformers.</p>

          <p>My setup is:<br>python = 3.9.7<br>GPU = A100 40gb<br>Transformers = 4.36.2<br>AutoAWQ
          = 0.1.8</p>

          '
        raw: 'Getting ```ValueError: OC is not a multiple of cta_N = 64``` at the
          line ```out = awq_inference_engine.gemm_forward_cuda(x.reshape(-1, x.shape[-1]),
          self.qweight, self.scales, self.qzeroes, 8)``` in the ```linear.py``` file
          from the ```AutoAWQ``` package. I am getting this error when loading the
          model in using Transformers.


          My setup is:

          python = 3.9.7

          GPU = A100 40gb

          Transformers = 4.36.2

          AutoAWQ = 0.1.8'
        updatedAt: '2024-01-19T17:00:04.322Z'
      numEdits: 2
      reactions: []
    id: 65aaaa7127f7d6995a66c088
    type: comment
  author: lazyDataScientist
  content: 'Getting ```ValueError: OC is not a multiple of cta_N = 64``` at the line
    ```out = awq_inference_engine.gemm_forward_cuda(x.reshape(-1, x.shape[-1]), self.qweight,
    self.scales, self.qzeroes, 8)``` in the ```linear.py``` file from the ```AutoAWQ```
    package. I am getting this error when loading the model in using Transformers.


    My setup is:

    python = 3.9.7

    GPU = A100 40gb

    Transformers = 4.36.2

    AutoAWQ = 0.1.8'
  created_at: 2024-01-19 16:59:29+00:00
  edited: true
  hidden: false
  id: 65aaaa7127f7d6995a66c088
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 5
repo_id: TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ
repo_type: model
status: open
target_branch: null
title: OC is not a multiple of cta_N = 64
