!!python/object:huggingface_hub.community.DiscussionWithDetails
author: andersgb1
conflicting_files: null
created_at: 2023-12-04 08:07:52+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/11ca14b5e947204ddfcffab36e19f43f.svg
      fullname: Anders Glent Buch
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: andersgb1
      type: user
    createdAt: '2023-12-04T08:07:52.000Z'
    data:
      edited: false
      editors:
      - andersgb1
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.5103982090950012
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/11ca14b5e947204ddfcffab36e19f43f.svg
          fullname: Anders Glent Buch
          isHf: false
          isPro: false
          name: andersgb1
          type: user
        html: "<p>I can't load the model on a freshly upgraded transformers. Am I\
          \ doing it wrong?</p>\n<p>The first variation looks like this:</p>\n<pre><code>&gt;&gt;&gt;\
          \ from transformers import pipeline\n&gt;&gt;&gt; pipe = pipeline(\"automatic-speech-recognition\"\
          , model=\"mhenrichsen/hviske\")\nTraceback (most recent call last):\n  File\
          \ \"&lt;stdin&gt;\", line 1, in &lt;module&gt;\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/__init__.py\"\
          , line 870, in pipeline\n    framework, model = infer_framework_load_model(\n\
          \  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/base.py\"\
          , line 282, in infer_framework_load_model\n    raise ValueError(\nValueError:\
          \ Could not load model mhenrichsen/hviske with any of the following classes:\
          \ (&lt;class 'transformers.models.auto.modeling_auto.AutoModelForCTC'&gt;,\
          \ &lt;class 'transformers.models.auto.modeling_auto.AutoModelForSpeechSeq2Seq'&gt;,\
          \ &lt;class 'transformers.models.whisper.modeling_whisper.WhisperForConditionalGeneration'&gt;).\
          \ See the original errors:\n\nwhile loading with AutoModelForCTC, an error\
          \ is thrown:\nTraceback (most recent call last):\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/base.py\"\
          , line 269, in infer_framework_load_model\n    model = model_class.from_pretrained(model,\
          \ **kwargs)\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py\"\
          , line 569, in from_pretrained\n    raise ValueError(\nValueError: Unrecognized\
          \ configuration class &lt;class 'transformers.models.whisper.configuration_whisper.WhisperConfig'&gt;\
          \ for this kind of AutoModel: AutoModelForCTC.\nModel type should be one\
          \ of Data2VecAudioConfig, HubertConfig, MCTCTConfig, SEWConfig, SEWDConfig,\
          \ UniSpeechConfig, UniSpeechSatConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig,\
          \ WavLMConfig.\n\nwhile loading with AutoModelForSpeechSeq2Seq, an error\
          \ is thrown:\nTraceback (most recent call last):\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/base.py\"\
          , line 269, in infer_framework_load_model\n    model = model_class.from_pretrained(model,\
          \ **kwargs)\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py\"\
          , line 566, in from_pretrained\n    return model_class.from_pretrained(\n\
          \  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/modeling_utils.py\"\
          , line 3128, in from_pretrained\n    resolved_archive_file, sharded_metadata\
          \ = get_checkpoint_shard_files(\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/utils/hub.py\"\
          , line 1029, in get_checkpoint_shard_files\n    index = json.loads(f.read())\n\
          \  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\n \
          \   return _default_decoder.decode(s)\n  File \"/usr/lib/python3.10/json/decoder.py\"\
          , line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n\
          \  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n\
          \    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n\
          json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\
          \nwhile loading with WhisperForConditionalGeneration, an error is thrown:\n\
          Traceback (most recent call last):\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/base.py\"\
          , line 269, in infer_framework_load_model\n    model = model_class.from_pretrained(model,\
          \ **kwargs)\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/modeling_utils.py\"\
          , line 3128, in from_pretrained\n    resolved_archive_file, sharded_metadata\
          \ = get_checkpoint_shard_files(\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/utils/hub.py\"\
          , line 1029, in get_checkpoint_shard_files\n    index = json.loads(f.read())\n\
          \  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\n \
          \   return _default_decoder.decode(s)\n  File \"/usr/lib/python3.10/json/decoder.py\"\
          , line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n\
          \  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n\
          \    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n\
          json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\
          </code></pre>\n<p>The second way gives JSON errors for both preprocessor\
          \ and model:</p>\n<pre><code>&gt;&gt;&gt; processor = AutoProcessor.from_pretrained(\"\
          mhenrichsen/hviske\")\nTraceback (most recent call last):\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/image_processing_utils.py\"\
          , line 362, in get_image_processor_dict\n    image_processor_dict = json.loads(text)\n\
          \  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\n \
          \   return _default_decoder.decode(s)\n  File \"/usr/lib/python3.10/json/decoder.py\"\
          , line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n\
          \  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n\
          \    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n\
          json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\
          \nDuring handling of the above exception, another exception occurred:\n\n\
          Traceback (most recent call last):\n  File \"&lt;stdin&gt;\", line 1, in\
          \ &lt;module&gt;\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/models/auto/processing_auto.py\"\
          , line 235, in from_pretrained\n    config_dict, _ = ImageProcessingMixin.get_image_processor_dict(pretrained_model_name_or_path,\
          \ **kwargs)\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/image_processing_utils.py\"\
          , line 365, in get_image_processor_dict\n    raise EnvironmentError(\nOSError:\
          \ It looks like the config file at '/home/[REDACTED]/.cache/huggingface/hub/models--mhenrichsen--hviske/snapshots/8ba076bccb13f36b6359921be2474d43059ce922/preprocessor_config.json'\
          \ is not a valid JSON file.\n\n&gt;&gt;&gt; model = AutoModelForSpeechSeq2Seq.from_pretrained(\"\
          mhenrichsen/hviske\")\nTraceback (most recent call last):\n  File \"&lt;stdin&gt;\"\
          , line 1, in &lt;module&gt;\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py\"\
          , line 566, in from_pretrained\n    return model_class.from_pretrained(\n\
          \  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/modeling_utils.py\"\
          , line 3128, in from_pretrained\n    resolved_archive_file, sharded_metadata\
          \ = get_checkpoint_shard_files(\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/utils/hub.py\"\
          , line 1029, in get_checkpoint_shard_files\n    index = json.loads(f.read())\n\
          \  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\n \
          \   return _default_decoder.decode(s)\n  File \"/usr/lib/python3.10/json/decoder.py\"\
          , line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n\
          \  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n\
          \    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n\
          json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\
          </code></pre>\n"
        raw: "I can't load the model on a freshly upgraded transformers. Am I doing\
          \ it wrong?\r\n\r\nThe first variation looks like this:\r\n```\r\n>>> from\
          \ transformers import pipeline\r\n>>> pipe = pipeline(\"automatic-speech-recognition\"\
          , model=\"mhenrichsen/hviske\")\r\nTraceback (most recent call last):\r\n\
          \  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/__init__.py\"\
          , line 870, in pipeline\r\n    framework, model = infer_framework_load_model(\r\
          \n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/base.py\"\
          , line 282, in infer_framework_load_model\r\n    raise ValueError(\r\nValueError:\
          \ Could not load model mhenrichsen/hviske with any of the following classes:\
          \ (<class 'transformers.models.auto.modeling_auto.AutoModelForCTC'>, <class\
          \ 'transformers.models.auto.modeling_auto.AutoModelForSpeechSeq2Seq'>, <class\
          \ 'transformers.models.whisper.modeling_whisper.WhisperForConditionalGeneration'>).\
          \ See the original errors:\r\n\r\nwhile loading with AutoModelForCTC, an\
          \ error is thrown:\r\nTraceback (most recent call last):\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/base.py\"\
          , line 269, in infer_framework_load_model\r\n    model = model_class.from_pretrained(model,\
          \ **kwargs)\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py\"\
          , line 569, in from_pretrained\r\n    raise ValueError(\r\nValueError: Unrecognized\
          \ configuration class <class 'transformers.models.whisper.configuration_whisper.WhisperConfig'>\
          \ for this kind of AutoModel: AutoModelForCTC.\r\nModel type should be one\
          \ of Data2VecAudioConfig, HubertConfig, MCTCTConfig, SEWConfig, SEWDConfig,\
          \ UniSpeechConfig, UniSpeechSatConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig,\
          \ WavLMConfig.\r\n\r\nwhile loading with AutoModelForSpeechSeq2Seq, an error\
          \ is thrown:\r\nTraceback (most recent call last):\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/base.py\"\
          , line 269, in infer_framework_load_model\r\n    model = model_class.from_pretrained(model,\
          \ **kwargs)\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py\"\
          , line 566, in from_pretrained\r\n    return model_class.from_pretrained(\r\
          \n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/modeling_utils.py\"\
          , line 3128, in from_pretrained\r\n    resolved_archive_file, sharded_metadata\
          \ = get_checkpoint_shard_files(\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/utils/hub.py\"\
          , line 1029, in get_checkpoint_shard_files\r\n    index = json.loads(f.read())\r\
          \n  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\r\n\
          \    return _default_decoder.decode(s)\r\n  File \"/usr/lib/python3.10/json/decoder.py\"\
          , line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\
          \n  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\r\
          \n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\
          \njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\r\
          \n\r\nwhile loading with WhisperForConditionalGeneration, an error is thrown:\r\
          \nTraceback (most recent call last):\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/base.py\"\
          , line 269, in infer_framework_load_model\r\n    model = model_class.from_pretrained(model,\
          \ **kwargs)\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/modeling_utils.py\"\
          , line 3128, in from_pretrained\r\n    resolved_archive_file, sharded_metadata\
          \ = get_checkpoint_shard_files(\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/utils/hub.py\"\
          , line 1029, in get_checkpoint_shard_files\r\n    index = json.loads(f.read())\r\
          \n  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\r\n\
          \    return _default_decoder.decode(s)\r\n  File \"/usr/lib/python3.10/json/decoder.py\"\
          , line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\
          \n  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\r\
          \n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\
          \njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\r\
          \n```\r\n\r\nThe second way gives JSON errors for both preprocessor and\
          \ model:\r\n```\r\n>>> processor = AutoProcessor.from_pretrained(\"mhenrichsen/hviske\"\
          )\r\nTraceback (most recent call last):\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/image_processing_utils.py\"\
          , line 362, in get_image_processor_dict\r\n    image_processor_dict = json.loads(text)\r\
          \n  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\r\n\
          \    return _default_decoder.decode(s)\r\n  File \"/usr/lib/python3.10/json/decoder.py\"\
          , line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\
          \n  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\r\
          \n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\
          \njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\r\
          \n\r\nDuring handling of the above exception, another exception occurred:\r\
          \n\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1,\
          \ in <module>\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/models/auto/processing_auto.py\"\
          , line 235, in from_pretrained\r\n    config_dict, _ = ImageProcessingMixin.get_image_processor_dict(pretrained_model_name_or_path,\
          \ **kwargs)\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/image_processing_utils.py\"\
          , line 365, in get_image_processor_dict\r\n    raise EnvironmentError(\r\
          \nOSError: It looks like the config file at '/home/[REDACTED]/.cache/huggingface/hub/models--mhenrichsen--hviske/snapshots/8ba076bccb13f36b6359921be2474d43059ce922/preprocessor_config.json'\
          \ is not a valid JSON file.\r\n\r\n>>> model = AutoModelForSpeechSeq2Seq.from_pretrained(\"\
          mhenrichsen/hviske\")\r\nTraceback (most recent call last):\r\n  File \"\
          <stdin>\", line 1, in <module>\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py\"\
          , line 566, in from_pretrained\r\n    return model_class.from_pretrained(\r\
          \n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/modeling_utils.py\"\
          , line 3128, in from_pretrained\r\n    resolved_archive_file, sharded_metadata\
          \ = get_checkpoint_shard_files(\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/utils/hub.py\"\
          , line 1029, in get_checkpoint_shard_files\r\n    index = json.loads(f.read())\r\
          \n  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\r\n\
          \    return _default_decoder.decode(s)\r\n  File \"/usr/lib/python3.10/json/decoder.py\"\
          , line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\
          \n  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\r\
          \n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\
          \njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\r\
          \n```"
        updatedAt: '2023-12-04T08:07:52.267Z'
      numEdits: 0
      reactions: []
    id: 656d88d88dffbab5af724608
    type: comment
  author: andersgb1
  content: "I can't load the model on a freshly upgraded transformers. Am I doing\
    \ it wrong?\r\n\r\nThe first variation looks like this:\r\n```\r\n>>> from transformers\
    \ import pipeline\r\n>>> pipe = pipeline(\"automatic-speech-recognition\", model=\"\
    mhenrichsen/hviske\")\r\nTraceback (most recent call last):\r\n  File \"<stdin>\"\
    , line 1, in <module>\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/__init__.py\"\
    , line 870, in pipeline\r\n    framework, model = infer_framework_load_model(\r\
    \n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/base.py\"\
    , line 282, in infer_framework_load_model\r\n    raise ValueError(\r\nValueError:\
    \ Could not load model mhenrichsen/hviske with any of the following classes: (<class\
    \ 'transformers.models.auto.modeling_auto.AutoModelForCTC'>, <class 'transformers.models.auto.modeling_auto.AutoModelForSpeechSeq2Seq'>,\
    \ <class 'transformers.models.whisper.modeling_whisper.WhisperForConditionalGeneration'>).\
    \ See the original errors:\r\n\r\nwhile loading with AutoModelForCTC, an error\
    \ is thrown:\r\nTraceback (most recent call last):\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/base.py\"\
    , line 269, in infer_framework_load_model\r\n    model = model_class.from_pretrained(model,\
    \ **kwargs)\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py\"\
    , line 569, in from_pretrained\r\n    raise ValueError(\r\nValueError: Unrecognized\
    \ configuration class <class 'transformers.models.whisper.configuration_whisper.WhisperConfig'>\
    \ for this kind of AutoModel: AutoModelForCTC.\r\nModel type should be one of\
    \ Data2VecAudioConfig, HubertConfig, MCTCTConfig, SEWConfig, SEWDConfig, UniSpeechConfig,\
    \ UniSpeechSatConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WavLMConfig.\r\n\
    \r\nwhile loading with AutoModelForSpeechSeq2Seq, an error is thrown:\r\nTraceback\
    \ (most recent call last):\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/base.py\"\
    , line 269, in infer_framework_load_model\r\n    model = model_class.from_pretrained(model,\
    \ **kwargs)\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py\"\
    , line 566, in from_pretrained\r\n    return model_class.from_pretrained(\r\n\
    \  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/modeling_utils.py\"\
    , line 3128, in from_pretrained\r\n    resolved_archive_file, sharded_metadata\
    \ = get_checkpoint_shard_files(\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/utils/hub.py\"\
    , line 1029, in get_checkpoint_shard_files\r\n    index = json.loads(f.read())\r\
    \n  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\r\n    return\
    \ _default_decoder.decode(s)\r\n  File \"/usr/lib/python3.10/json/decoder.py\"\
    , line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\
    \n  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\r\n\
    \    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError:\
    \ Expecting value: line 1 column 1 (char 0)\r\n\r\nwhile loading with WhisperForConditionalGeneration,\
    \ an error is thrown:\r\nTraceback (most recent call last):\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/pipelines/base.py\"\
    , line 269, in infer_framework_load_model\r\n    model = model_class.from_pretrained(model,\
    \ **kwargs)\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/modeling_utils.py\"\
    , line 3128, in from_pretrained\r\n    resolved_archive_file, sharded_metadata\
    \ = get_checkpoint_shard_files(\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/utils/hub.py\"\
    , line 1029, in get_checkpoint_shard_files\r\n    index = json.loads(f.read())\r\
    \n  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\r\n    return\
    \ _default_decoder.decode(s)\r\n  File \"/usr/lib/python3.10/json/decoder.py\"\
    , line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\
    \n  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\r\n\
    \    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError:\
    \ Expecting value: line 1 column 1 (char 0)\r\n```\r\n\r\nThe second way gives\
    \ JSON errors for both preprocessor and model:\r\n```\r\n>>> processor = AutoProcessor.from_pretrained(\"\
    mhenrichsen/hviske\")\r\nTraceback (most recent call last):\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/image_processing_utils.py\"\
    , line 362, in get_image_processor_dict\r\n    image_processor_dict = json.loads(text)\r\
    \n  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\r\n    return\
    \ _default_decoder.decode(s)\r\n  File \"/usr/lib/python3.10/json/decoder.py\"\
    , line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\
    \n  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\r\n\
    \    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError:\
    \ Expecting value: line 1 column 1 (char 0)\r\n\r\nDuring handling of the above\
    \ exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\
    \n  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/models/auto/processing_auto.py\"\
    , line 235, in from_pretrained\r\n    config_dict, _ = ImageProcessingMixin.get_image_processor_dict(pretrained_model_name_or_path,\
    \ **kwargs)\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/image_processing_utils.py\"\
    , line 365, in get_image_processor_dict\r\n    raise EnvironmentError(\r\nOSError:\
    \ It looks like the config file at '/home/[REDACTED]/.cache/huggingface/hub/models--mhenrichsen--hviske/snapshots/8ba076bccb13f36b6359921be2474d43059ce922/preprocessor_config.json'\
    \ is not a valid JSON file.\r\n\r\n>>> model = AutoModelForSpeechSeq2Seq.from_pretrained(\"\
    mhenrichsen/hviske\")\r\nTraceback (most recent call last):\r\n  File \"<stdin>\"\
    , line 1, in <module>\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py\"\
    , line 566, in from_pretrained\r\n    return model_class.from_pretrained(\r\n\
    \  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/modeling_utils.py\"\
    , line 3128, in from_pretrained\r\n    resolved_archive_file, sharded_metadata\
    \ = get_checkpoint_shard_files(\r\n  File \"/home/[REDACTED]/.local/lib/python3.10/site-packages/transformers/utils/hub.py\"\
    , line 1029, in get_checkpoint_shard_files\r\n    index = json.loads(f.read())\r\
    \n  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\r\n    return\
    \ _default_decoder.decode(s)\r\n  File \"/usr/lib/python3.10/json/decoder.py\"\
    , line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\
    \n  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\r\n\
    \    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError:\
    \ Expecting value: line 1 column 1 (char 0)\r\n```"
  created_at: 2023-12-04 08:07:52+00:00
  edited: false
  hidden: false
  id: 656d88d88dffbab5af724608
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/2f7a1cfc68e6f5c0a7ddb323d2ffd252.svg
      fullname: Mads
      isHf: false
      isOrgMember: false
      isOwner: true
      isPro: false
      name: mhenrichsen
      type: user
    createdAt: '2023-12-04T09:05:38.000Z'
    data:
      edited: false
      editors:
      - mhenrichsen
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.9616852402687073
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/2f7a1cfc68e6f5c0a7ddb323d2ffd252.svg
          fullname: Mads
          isHf: false
          isPro: false
          name: mhenrichsen
          type: user
        html: "<p><span data-props=\"{&quot;user&quot;:&quot;andersgb1&quot;}\" data-target=\"\
          UserMention\" class=\"SVELTE_PARTIAL_HYDRATER contents\">\n\n<span class=\"\
          inline-block\"><span class=\"contents\"><a href=\"/andersgb1\">@<span class=\"\
          underline\">andersgb1</span></a></span>\n\n\t</span></span> the error is\
          \ on my end. Currently at work, but will upload a new version tonight.</p>\n"
        raw: '@andersgb1 the error is on my end. Currently at work, but will upload
          a new version tonight.'
        updatedAt: '2023-12-04T09:05:38.792Z'
      numEdits: 0
      reactions:
      - count: 1
        reaction: "\u2764\uFE0F"
        users:
        - sheikhomar
    id: 656d9662c4d6794d7fab1c7d
    type: comment
  author: mhenrichsen
  content: '@andersgb1 the error is on my end. Currently at work, but will upload
    a new version tonight.'
  created_at: 2023-12-04 09:05:38+00:00
  edited: false
  hidden: false
  id: 656d9662c4d6794d7fab1c7d
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/11ca14b5e947204ddfcffab36e19f43f.svg
      fullname: Anders Glent Buch
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: andersgb1
      type: user
    createdAt: '2023-12-04T09:51:52.000Z'
    data:
      edited: false
      editors:
      - andersgb1
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.9011057615280151
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/11ca14b5e947204ddfcffab36e19f43f.svg
          fullname: Anders Glent Buch
          isHf: false
          isPro: false
          name: andersgb1
          type: user
        html: "<p><span data-props=\"{&quot;user&quot;:&quot;mhenrichsen&quot;}\"\
          \ data-target=\"UserMention\" class=\"SVELTE_PARTIAL_HYDRATER contents\"\
          >\n\n<span class=\"inline-block\"><span class=\"contents\"><a href=\"/mhenrichsen\"\
          >@<span class=\"underline\">mhenrichsen</span></a></span>\n\n\t</span></span>\
          \ nice, thanks - looking forward to trying it out!</p>\n"
        raw: '@mhenrichsen nice, thanks - looking forward to trying it out!'
        updatedAt: '2023-12-04T09:51:52.491Z'
      numEdits: 0
      reactions: []
    id: 656da13879a834846b195b93
    type: comment
  author: andersgb1
  content: '@mhenrichsen nice, thanks - looking forward to trying it out!'
  created_at: 2023-12-04 09:51:52+00:00
  edited: false
  hidden: false
  id: 656da13879a834846b195b93
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/2f7a1cfc68e6f5c0a7ddb323d2ffd252.svg
      fullname: Mads
      isHf: false
      isOrgMember: false
      isOwner: true
      isPro: false
      name: mhenrichsen
      type: user
    createdAt: '2023-12-09T11:20:44.000Z'
    data:
      edited: false
      editors:
      - mhenrichsen
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.9865351915359497
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/2f7a1cfc68e6f5c0a7ddb323d2ffd252.svg
          fullname: Mads
          isHf: false
          isPro: false
          name: mhenrichsen
          type: user
        html: "<p><span data-props=\"{&quot;user&quot;:&quot;andersgb1&quot;}\" data-target=\"\
          UserMention\" class=\"SVELTE_PARTIAL_HYDRATER contents\">\n\n<span class=\"\
          inline-block\"><span class=\"contents\"><a href=\"/andersgb1\">@<span class=\"\
          underline\">andersgb1</span></a></span>\n\n\t</span></span> the model has\
          \ been retrained and reuploaded :) Works fine now.</p>\n"
        raw: '@andersgb1 the model has been retrained and reuploaded :) Works fine
          now.'
        updatedAt: '2023-12-09T11:20:44.287Z'
      numEdits: 0
      reactions:
      - count: 1
        reaction: "\U0001F44D"
        users:
        - mathiasn1
    id: 65744d8c5f7efec0ae1c5c08
    type: comment
  author: mhenrichsen
  content: '@andersgb1 the model has been retrained and reuploaded :) Works fine now.'
  created_at: 2023-12-09 11:20:44+00:00
  edited: false
  hidden: false
  id: 65744d8c5f7efec0ae1c5c08
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 1
repo_id: mhenrichsen/hviske
repo_type: model
status: open
target_branch: null
title: Cannot load model
