!!python/object:huggingface_hub.community.DiscussionWithDetails
author: Gback
conflicting_files: null
created_at: 2023-05-02 16:06:38+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/8b5560e4ffcc5aa98d2c40cb8afa2506.svg
      fullname: Georg Back
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: Gback
      type: user
    createdAt: '2023-05-02T17:06:38.000Z'
    data:
      edited: false
      editors:
      - Gback
      hidden: false
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/8b5560e4ffcc5aa98d2c40cb8afa2506.svg
          fullname: Georg Back
          isHf: false
          isPro: false
          name: Gback
          type: user
        html: '<p>I have used AutoModels and DNA_bert before (a few months ago) without
          any problems.<br>However, now all AutoModels fail to load with the error:<br>"Unrecognized
          configuration class &lt;class ''transformers_modules.zhihan1996.DNA_bert_6.6af99bac8f2aada050efd70285c526b151ecd360.configuration_bert.BertConfig''&gt;
          for this kind of AutoModel: TFAutoModelForSequenceClassification"</p>

          <p>It seems that the current config is not recognized as BertConfig.</p>

          <p>Is it possible to fix this issue, or make the old version (with the old
          config) accessible?</p>

          '
        raw: "I have used AutoModels and DNA_bert before (a few months ago) without\
          \ any problems.\r\nHowever, now all AutoModels fail to load with the error:\r\
          \n\"Unrecognized configuration class <class 'transformers_modules.zhihan1996.DNA_bert_6.6af99bac8f2aada050efd70285c526b151ecd360.configuration_bert.BertConfig'>\
          \ for this kind of AutoModel: TFAutoModelForSequenceClassification\"\r\n\
          \r\nIt seems that the current config is not recognized as BertConfig.\r\n\
          \r\nIs it possible to fix this issue, or make the old version (with the\
          \ old config) accessible?\r\n\r\n"
        updatedAt: '2023-05-02T17:06:38.205Z'
      numEdits: 0
      reactions: []
    id: 6451431ef800611f94f26bf7
    type: comment
  author: Gback
  content: "I have used AutoModels and DNA_bert before (a few months ago) without\
    \ any problems.\r\nHowever, now all AutoModels fail to load with the error:\r\n\
    \"Unrecognized configuration class <class 'transformers_modules.zhihan1996.DNA_bert_6.6af99bac8f2aada050efd70285c526b151ecd360.configuration_bert.BertConfig'>\
    \ for this kind of AutoModel: TFAutoModelForSequenceClassification\"\r\n\r\nIt\
    \ seems that the current config is not recognized as BertConfig.\r\n\r\nIs it\
    \ possible to fix this issue, or make the old version (with the old config) accessible?\r\
    \n\r\n"
  created_at: 2023-05-02 16:06:38+00:00
  edited: false
  hidden: false
  id: 6451431ef800611f94f26bf7
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/81612e74b74a5dd06ccae7dc858d7721.svg
      fullname: Zhihan Zhou
      isHf: false
      isOrgMember: false
      isOwner: true
      isPro: false
      name: zhihan1996
      type: user
    createdAt: '2023-05-02T20:18:24.000Z'
    data:
      edited: false
      editors:
      - zhihan1996
      hidden: false
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/81612e74b74a5dd06ccae7dc858d7721.svg
          fullname: Zhihan Zhou
          isHf: false
          isPro: false
          name: zhihan1996
          type: user
        html: '<p>Thanks for raising the issue and for your interest in this work.
          It works now.</p>

          '
        raw: Thanks for raising the issue and for your interest in this work. It works
          now.
        updatedAt: '2023-05-02T20:18:24.887Z'
      numEdits: 0
      reactions:
      - count: 1
        reaction: "\U0001F44D"
        users:
        - Gback
    id: 645170109d916c596e32390e
    type: comment
  author: zhihan1996
  content: Thanks for raising the issue and for your interest in this work. It works
    now.
  created_at: 2023-05-02 19:18:24+00:00
  edited: false
  hidden: false
  id: 645170109d916c596e32390e
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 4
repo_id: zhihan1996/DNA_bert_6
repo_type: model
status: open
target_branch: null
title: Since the recent update, AutoModel for any DNA_bert model does not work anymore
