!!python/object:huggingface_hub.community.DiscussionWithDetails
author: samu
conflicting_files: null
created_at: 2023-08-29 07:16:00+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/900e751907c8dc2035e806f727800ef3.svg
      fullname: Samuel Lukudu
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: samu
      type: user
    createdAt: '2023-08-29T08:16:00.000Z'
    data:
      edited: false
      editors:
      - samu
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.7031135559082031
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/900e751907c8dc2035e806f727800ef3.svg
          fullname: Samuel Lukudu
          isHf: false
          isPro: false
          name: samu
          type: user
        html: '<p>When push_to_hub=True, I get this error: </p>

          <p><a rel="nofollow" href="https://cdn-uploads.huggingface.co/production/uploads/615ce9a95db25883c685c10d/BZ6KgbBdUqLN05QKNT7c_.png"><img
          alt="train-args-vit.png" src="https://cdn-uploads.huggingface.co/production/uploads/615ce9a95db25883c685c10d/BZ6KgbBdUqLN05QKNT7c_.png"></a></p>

          <p><a rel="nofollow" href="https://cdn-uploads.huggingface.co/production/uploads/615ce9a95db25883c685c10d/6t1B5LC6QfCw6nzSntvAv.png"><img
          alt="vit-hub-upload-error.png" src="https://cdn-uploads.huggingface.co/production/uploads/615ce9a95db25883c685c10d/6t1B5LC6QfCw6nzSntvAv.png"></a></p>

          <p>But when I comment out push_to_hub, the model is able to train without
          any errors. And this is the same for using pipeline as well. What could
          be the problem?</p>

          '
        raw: "When push_to_hub=True, I get this error: \r\n\r\n![train-args-vit.png](https://cdn-uploads.huggingface.co/production/uploads/615ce9a95db25883c685c10d/BZ6KgbBdUqLN05QKNT7c_.png)\r\
          \n\r\n![vit-hub-upload-error.png](https://cdn-uploads.huggingface.co/production/uploads/615ce9a95db25883c685c10d/6t1B5LC6QfCw6nzSntvAv.png)\r\
          \n\r\nBut when I comment out push_to_hub, the model is able to train without\
          \ any errors. And this is the same for using pipeline as well. What could\
          \ be the problem?\r\n"
        updatedAt: '2023-08-29T08:16:00.926Z'
      numEdits: 0
      reactions: []
    id: 64eda9400345c2de92051c89
    type: comment
  author: samu
  content: "When push_to_hub=True, I get this error: \r\n\r\n![train-args-vit.png](https://cdn-uploads.huggingface.co/production/uploads/615ce9a95db25883c685c10d/BZ6KgbBdUqLN05QKNT7c_.png)\r\
    \n\r\n![vit-hub-upload-error.png](https://cdn-uploads.huggingface.co/production/uploads/615ce9a95db25883c685c10d/6t1B5LC6QfCw6nzSntvAv.png)\r\
    \n\r\nBut when I comment out push_to_hub, the model is able to train without any\
    \ errors. And this is the same for using pipeline as well. What could be the problem?\r\
    \n"
  created_at: 2023-08-29 07:16:00+00:00
  edited: false
  hidden: false
  id: 64eda9400345c2de92051c89
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/900e751907c8dc2035e806f727800ef3.svg
      fullname: Samuel Lukudu
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: samu
      type: user
    createdAt: '2023-09-02T01:26:35.000Z'
    data:
      edited: false
      editors:
      - samu
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.9475572109222412
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/900e751907c8dc2035e806f727800ef3.svg
          fullname: Samuel Lukudu
          isHf: false
          isPro: false
          name: samu
          type: user
        html: '<p>I was reading token instead of write token. Now, am able to push
          checkpoints to the hub</p>

          '
        raw: I was reading token instead of write token. Now, am able to push checkpoints
          to the hub
        updatedAt: '2023-09-02T01:26:35.945Z'
      numEdits: 0
      reactions:
      - count: 1
        reaction: "\U0001F91D"
        users:
        - lysandre
      relatedEventId: 64f28f4bd18db398ab3d51ef
    id: 64f28f4bd18db398ab3d51ed
    type: comment
  author: samu
  content: I was reading token instead of write token. Now, am able to push checkpoints
    to the hub
  created_at: 2023-09-02 00:26:35+00:00
  edited: false
  hidden: false
  id: 64f28f4bd18db398ab3d51ed
  type: comment
- !!python/object:huggingface_hub.community.DiscussionStatusChange
  _event:
    author:
      avatarUrl: /avatars/900e751907c8dc2035e806f727800ef3.svg
      fullname: Samuel Lukudu
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: samu
      type: user
    createdAt: '2023-09-02T01:26:35.000Z'
    data:
      status: closed
    id: 64f28f4bd18db398ab3d51ef
    type: status-change
  author: samu
  created_at: 2023-09-02 00:26:35+00:00
  id: 64f28f4bd18db398ab3d51ef
  new_status: closed
  type: status-change
is_pull_request: false
merge_commit_oid: null
num: 11
repo_id: google/vit-base-patch16-224
repo_type: model
status: closed
target_branch: null
title: Issue with uploading model check points to the hub for google/vit-base-patch16-224-in21k
