!!python/object:huggingface_hub.community.DiscussionWithDetails
author: pavankay
conflicting_files: null
created_at: 2024-01-08 02:29:58+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/0fb305008f0e10481034b3e36ebc4a0b.svg
      fullname: Pavan Kay
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: pavankay
      type: user
    createdAt: '2024-01-08T02:29:58.000Z'
    data:
      edited: false
      editors:
      - pavankay
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.7021408677101135
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/0fb305008f0e10481034b3e36ebc4a0b.svg
          fullname: Pavan Kay
          isHf: false
          isPro: false
          name: pavankay
          type: user
        html: "<p>when I run pip install git+<a rel=\"nofollow\" href=\"https://github.com/huggingface/diffusers@@shap-ee\"\
          >https://github.com/huggingface/diffusers@@shap-ee</a> I get this error\
          \ </p>\n<p>(shap-e) C:\\Users\\name&gt;pip install git+<a rel=\"nofollow\"\
          \ href=\"https://github.com/huggingface/diffusers@@shap-ee\">https://github.com/huggingface/diffusers@@shap-ee</a><br>Defaulting\
          \ to user installation because normal site-packages is not writeable<br>Collecting\
          \ git+<a rel=\"nofollow\" href=\"https://github.com/huggingface/diffusers@@shap-ee\"\
          >https://github.com/huggingface/diffusers@@shap-ee</a><br>  Cloning <a rel=\"\
          nofollow\" href=\"https://github.com/huggingface/diffusers@\">https://github.com/huggingface/diffusers@</a>\
          \ (to revision shap-ee) to c:\\users\\name\\appdata\\local\\temp\\pip-req-build-qzl6zef9<br>\
          \  Running command git clone --filter=blob:none --quiet <a rel=\"nofollow\"\
          \ href=\"https://github.com/huggingface/diffusers@\">https://github.com/huggingface/diffusers@</a>\
          \ 'C:\\Users\\name\\AppData\\Local\\Temp\\pip-req-build-qzl6zef9'<br>  remote:\
          \ Repository not found.<br>  fatal: repository '<a rel=\"nofollow\" href=\"\
          https://github.com/huggingface/diffusers@/'\">https://github.com/huggingface/diffusers@/'</a>\
          \ not found<br>  error: subprocess-exited-with-error</p>\n<p>  \xD7 git\
          \ clone --filter=blob:none --quiet <a rel=\"nofollow\" href=\"https://github.com/huggingface/diffusers@\"\
          >https://github.com/huggingface/diffusers@</a> 'C:\\Users\\name\\AppData\\\
          Local\\Temp\\pip-req-build-qzl6zef9' did not run successfully.<br>  \u2502\
          \ exit code: 128<br>  \u2570\u2500&gt; See above for output.</p>\n<p>  note:\
          \ This error originates from a subprocess, and is likely not a problem with\
          \ pip.<br>error: subprocess-exited-with-error</p>\n<p>\xD7 git clone --filter=blob:none\
          \ --quiet <a rel=\"nofollow\" href=\"https://github.com/huggingface/diffusers@\"\
          >https://github.com/huggingface/diffusers@</a> 'C:\\Users\\name\\AppData\\\
          Local\\Temp\\pip-req-build-qzl6zef9' did not run successfully.<br>\u2502\
          \ exit code: 128<br>\u2570\u2500&gt; See above for output.</p>\n<p>note:\
          \ This error originates from a subprocess, and is likely not a problem with\
          \ pip.</p>\n<p>(shap-e) C:\\Users\\name&gt;</p>\n"
        raw: "when I run pip install git+https://github.com/huggingface/diffusers@@shap-ee\
          \ I get this error \r\n\r\n(shap-e) C:\\Users\\name>pip install git+https://github.com/huggingface/diffusers@@shap-ee\r\
          \nDefaulting to user installation because normal site-packages is not writeable\r\
          \nCollecting git+https://github.com/huggingface/diffusers@@shap-ee\r\n \
          \ Cloning https://github.com/huggingface/diffusers@ (to revision shap-ee)\
          \ to c:\\users\\name\\appdata\\local\\temp\\pip-req-build-qzl6zef9\r\n \
          \ Running command git clone --filter=blob:none --quiet https://github.com/huggingface/diffusers@\
          \ 'C:\\Users\\name\\AppData\\Local\\Temp\\pip-req-build-qzl6zef9'\r\n  remote:\
          \ Repository not found.\r\n  fatal: repository 'https://github.com/huggingface/diffusers@/'\
          \ not found\r\n  error: subprocess-exited-with-error\r\n\r\n  \xD7 git clone\
          \ --filter=blob:none --quiet https://github.com/huggingface/diffusers@ 'C:\\\
          Users\\name\\AppData\\Local\\Temp\\pip-req-build-qzl6zef9' did not run successfully.\r\
          \n  \u2502 exit code: 128\r\n  \u2570\u2500> See above for output.\r\n\r\
          \n  note: This error originates from a subprocess, and is likely not a problem\
          \ with pip.\r\nerror: subprocess-exited-with-error\r\n\r\n\xD7 git clone\
          \ --filter=blob:none --quiet https://github.com/huggingface/diffusers@ 'C:\\\
          Users\\name\\AppData\\Local\\Temp\\pip-req-build-qzl6zef9' did not run successfully.\r\
          \n\u2502 exit code: 128\r\n\u2570\u2500> See above for output.\r\n\r\nnote:\
          \ This error originates from a subprocess, and is likely not a problem with\
          \ pip.\r\n\r\n(shap-e) C:\\Users\\name>"
        updatedAt: '2024-01-08T02:29:58.991Z'
      numEdits: 0
      reactions: []
    id: 659b5e26d3f21374155a4b12
    type: comment
  author: pavankay
  content: "when I run pip install git+https://github.com/huggingface/diffusers@@shap-ee\
    \ I get this error \r\n\r\n(shap-e) C:\\Users\\name>pip install git+https://github.com/huggingface/diffusers@@shap-ee\r\
    \nDefaulting to user installation because normal site-packages is not writeable\r\
    \nCollecting git+https://github.com/huggingface/diffusers@@shap-ee\r\n  Cloning\
    \ https://github.com/huggingface/diffusers@ (to revision shap-ee) to c:\\users\\\
    name\\appdata\\local\\temp\\pip-req-build-qzl6zef9\r\n  Running command git clone\
    \ --filter=blob:none --quiet https://github.com/huggingface/diffusers@ 'C:\\Users\\\
    name\\AppData\\Local\\Temp\\pip-req-build-qzl6zef9'\r\n  remote: Repository not\
    \ found.\r\n  fatal: repository 'https://github.com/huggingface/diffusers@/' not\
    \ found\r\n  error: subprocess-exited-with-error\r\n\r\n  \xD7 git clone --filter=blob:none\
    \ --quiet https://github.com/huggingface/diffusers@ 'C:\\Users\\name\\AppData\\\
    Local\\Temp\\pip-req-build-qzl6zef9' did not run successfully.\r\n  \u2502 exit\
    \ code: 128\r\n  \u2570\u2500> See above for output.\r\n\r\n  note: This error\
    \ originates from a subprocess, and is likely not a problem with pip.\r\nerror:\
    \ subprocess-exited-with-error\r\n\r\n\xD7 git clone --filter=blob:none --quiet\
    \ https://github.com/huggingface/diffusers@ 'C:\\Users\\name\\AppData\\Local\\\
    Temp\\pip-req-build-qzl6zef9' did not run successfully.\r\n\u2502 exit code: 128\r\
    \n\u2570\u2500> See above for output.\r\n\r\nnote: This error originates from\
    \ a subprocess, and is likely not a problem with pip.\r\n\r\n(shap-e) C:\\Users\\\
    name>"
  created_at: 2024-01-08 02:29:58+00:00
  edited: false
  hidden: false
  id: 659b5e26d3f21374155a4b12
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 10
repo_id: openai/shap-e-img2img
repo_type: model
status: open
target_branch: null
title: Error
