!!python/object:huggingface_hub.community.DiscussionWithDetails
author: mxkrn
conflicting_files: null
created_at: 2023-05-09 09:18:13+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/2638e6fec0f7a3bf24218e59d5656e2c.svg
      fullname: Max Kraan
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: mxkrn
      type: user
    createdAt: '2023-05-09T10:18:13.000Z'
    data:
      edited: false
      editors:
      - mxkrn
      hidden: false
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/2638e6fec0f7a3bf24218e59d5656e2c.svg
          fullname: Max Kraan
          isHf: false
          isPro: false
          name: mxkrn
          type: user
        html: '<p>I''m receiving a 504 Gateway Timeout error when trying to load this
          model via the API. This came up this morning when I tried to relaunch the
          application that''s using this model, it was working fine yesterday</p>

          <p>To reproduce:</p>

          <pre><code>from transformers import AutoModel


          model = AutoModel.from_pretrained("m-a-p/MERT-v1-330M", trust_remote_code=True)

          </code></pre>

          '
        raw: "I'm receiving a 504 Gateway Timeout error when trying to load this model\
          \ via the API. This came up this morning when I tried to relaunch the application\
          \ that's using this model, it was working fine yesterday\r\n\r\nTo reproduce:\r\
          \n```\r\nfrom transformers import AutoModel\r\n\r\nmodel = AutoModel.from_pretrained(\"\
          m-a-p/MERT-v1-330M\", trust_remote_code=True)\r\n```"
        updatedAt: '2023-05-09T10:18:13.503Z'
      numEdits: 0
      reactions: []
    id: 645a1de58c5bb23629a84050
    type: comment
  author: mxkrn
  content: "I'm receiving a 504 Gateway Timeout error when trying to load this model\
    \ via the API. This came up this morning when I tried to relaunch the application\
    \ that's using this model, it was working fine yesterday\r\n\r\nTo reproduce:\r\
    \n```\r\nfrom transformers import AutoModel\r\n\r\nmodel = AutoModel.from_pretrained(\"\
    m-a-p/MERT-v1-330M\", trust_remote_code=True)\r\n```"
  created_at: 2023-05-09 09:18:13+00:00
  edited: false
  hidden: false
  id: 645a1de58c5bb23629a84050
  type: comment
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/2638e6fec0f7a3bf24218e59d5656e2c.svg
      fullname: Max Kraan
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: mxkrn
      type: user
    createdAt: '2023-05-09T10:47:23.000Z'
    data:
      edited: true
      editors:
      - mxkrn
      hidden: false
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/2638e6fec0f7a3bf24218e59d5656e2c.svg
          fullname: Max Kraan
          isHf: false
          isPro: false
          name: mxkrn
          type: user
        html: '<p>Closing this again, it seems like it was related to HF downtime.
          I had tested that this wasn''t the case by trying to load other models but
          it seems like after resetting this error was also resolved.</p>

          '
        raw: Closing this again, it seems like it was related to HF downtime. I had
          tested that this wasn't the case by trying to load other models but it seems
          like after resetting this error was also resolved.
        updatedAt: '2023-05-09T10:47:41.213Z'
      numEdits: 1
      reactions: []
      relatedEventId: 645a24bb3e0a2e86e7080ce6
    id: 645a24bb3e0a2e86e7080ce5
    type: comment
  author: mxkrn
  content: Closing this again, it seems like it was related to HF downtime. I had
    tested that this wasn't the case by trying to load other models but it seems like
    after resetting this error was also resolved.
  created_at: 2023-05-09 09:47:23+00:00
  edited: true
  hidden: false
  id: 645a24bb3e0a2e86e7080ce5
  type: comment
- !!python/object:huggingface_hub.community.DiscussionStatusChange
  _event:
    author:
      avatarUrl: /avatars/2638e6fec0f7a3bf24218e59d5656e2c.svg
      fullname: Max Kraan
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: mxkrn
      type: user
    createdAt: '2023-05-09T10:47:23.000Z'
    data:
      status: closed
    id: 645a24bb3e0a2e86e7080ce6
    type: status-change
  author: mxkrn
  created_at: 2023-05-09 09:47:23+00:00
  id: 645a24bb3e0a2e86e7080ce6
  new_status: closed
  type: status-change
is_pull_request: false
merge_commit_oid: null
num: 2
repo_id: m-a-p/MERT-v1-330M
repo_type: model
status: closed
target_branch: null
title: 504 Gateway Timeout
