!!python/object:huggingface_hub.community.DiscussionWithDetails
author: deedeeharris
conflicting_files: null
created_at: 2023-10-05 19:03:24+00:00
diff: null
endpoint: https://huggingface.co
events:
- !!python/object:huggingface_hub.community.DiscussionComment
  _event:
    author:
      avatarUrl: /avatars/2e1ed1393e758c4e9c5474b1565bc537.svg
      fullname: Deedee Harris
      isHf: false
      isOrgMember: false
      isOwner: false
      isPro: false
      name: deedeeharris
      type: user
    createdAt: '2023-10-05T20:03:24.000Z'
    data:
      edited: false
      editors:
      - deedeeharris
      hidden: false
      identifiedLanguage:
        language: en
        probability: 0.7012824416160583
      isReport: false
      latest:
        author:
          avatarUrl: /avatars/2e1ed1393e758c4e9c5474b1565bc537.svg
          fullname: Deedee Harris
          isHf: false
          isPro: false
          name: deedeeharris
          type: user
        html: "<p>Hey there.<br>I've been using this model for Hebrew Diarization.\
          \ It was working fine. Recently I'm getting this error:</p>\n<p>2023-10-05\
          \ 19:59:13.529821: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38]\
          \ TF-TRT Warning: Could not find TensorRT<br>Lightning automatically upgraded\
          \ your loaded checkpoint from v1.5.4 to v2.0.9.post0. To apply the upgrade\
          \ to your files permanently, run <code>python -m pytorch_lightning.utilities.upgrade_checkpoint\
          \ --file ../root/.cache/torch/whisperx-vad-segmentation.bin</code><br>Model\
          \ was trained with pyannote.audio 0.0.1, yours is 3.0.0. Bad things might\
          \ happen unless you revert pyannote.audio to 0.x.</p>\n<blockquote>\n<blockquote>\n\
          <p>Performing transcription...<br>Downloading (\u2026)rocessor_config.json:\
          \ 100% 158/158 [00:00&lt;00:00, 586kB/s]<br>Downloading (\u2026)okenizer_config.json:\
          \ 100% 240/240 [00:00&lt;00:00, 1.04MB/s]<br>Downloading (\u2026)lve/main/config.json:\
          \ 100% 1.56k/1.56k [00:00&lt;00:00, 6.70MB/s]<br>Downloading (\u2026)olve/main/vocab.json:\
          \ 100% 304/304 [00:00&lt;00:00, 1.88MB/s]<br>Downloading (\u2026)in/added_tokens.json:\
          \ 100% 36.0/36.0 [00:00&lt;00:00, 181kB/s]<br>Downloading (\u2026)cial_tokens_map.json:\
          \ 100% 85.0/85.0 [00:00&lt;00:00, 625kB/s]<br>Special tokens have been added\
          \ in the vocabulary, make sure the associated word embeddings are fine-tuned\
          \ or trained.<br>Downloading model.safetensors: 100% 1.26G/1.26G [00:31&lt;00:00,\
          \ 39.5MB/s]<br>Performing alignment...<br>Traceback (most recent call last):<br>\
          \  File \"/usr/local/bin/whisperx\", line 8, in <br>    sys.exit(cli())<br>\
          \  File \"/usr/local/lib/python3.10/dist-packages/whisperx/transcribe.py\"\
          , line 195, in cli<br>    result = align(result[\"segments\"], align_model,\
          \ align_metadata, input_audio, device, interpolate_method=interpolate_method,\
          \ return_char_alignments=return_char_alignments, print_progress=print_progress)<br>\
          \  File \"/usr/local/lib/python3.10/dist-packages/whisperx/alignment.py\"\
          , line 227, in align<br>    trellis = get_trellis(emission, tokens, blank_id)<br>\
          \  File \"/usr/local/lib/python3.10/dist-packages/whisperx/alignment.py\"\
          , line 359, in get_trellis<br>    trellis[t, 1:] + emission[t, blank_id],<br>IndexError:\
          \ index 33 is out of bounds for dimension 1 with size 31<br>Execution time:\
          \ 93.00095582008362 seconds</p>\n</blockquote>\n</blockquote>\n<p>But, when\
          \ I use your other model (imvladikon/wav2vec2-xls-r-300m-lm-hebrew), I don't\
          \ get the error. </p>\n<p>Has there been some change that's causing the\
          \ error?</p>\n<p>Thanks</p>\n"
        raw: "Hey there.\r\nI've been using this model for Hebrew Diarization. It\
          \ was working fine. Recently I'm getting this error:\r\n\r\n2023-10-05 19:59:13.529821:\
          \ W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning:\
          \ Could not find TensorRT\r\nLightning automatically upgraded your loaded\
          \ checkpoint from v1.5.4 to v2.0.9.post0. To apply the upgrade to your files\
          \ permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint\
          \ --file ../root/.cache/torch/whisperx-vad-segmentation.bin`\r\nModel was\
          \ trained with pyannote.audio 0.0.1, yours is 3.0.0. Bad things might happen\
          \ unless you revert pyannote.audio to 0.x.\r\n>>Performing transcription...\r\
          \nDownloading (\u2026)rocessor_config.json: 100% 158/158 [00:00<00:00, 586kB/s]\r\
          \nDownloading (\u2026)okenizer_config.json: 100% 240/240 [00:00<00:00, 1.04MB/s]\r\
          \nDownloading (\u2026)lve/main/config.json: 100% 1.56k/1.56k [00:00<00:00,\
          \ 6.70MB/s]\r\nDownloading (\u2026)olve/main/vocab.json: 100% 304/304 [00:00<00:00,\
          \ 1.88MB/s]\r\nDownloading (\u2026)in/added_tokens.json: 100% 36.0/36.0\
          \ [00:00<00:00, 181kB/s]\r\nDownloading (\u2026)cial_tokens_map.json: 100%\
          \ 85.0/85.0 [00:00<00:00, 625kB/s]\r\nSpecial tokens have been added in\
          \ the vocabulary, make sure the associated word embeddings are fine-tuned\
          \ or trained.\r\nDownloading model.safetensors: 100% 1.26G/1.26G [00:31<00:00,\
          \ 39.5MB/s]\r\n>>Performing alignment...\r\nTraceback (most recent call\
          \ last):\r\n  File \"/usr/local/bin/whisperx\", line 8, in <module>\r\n\
          \    sys.exit(cli())\r\n  File \"/usr/local/lib/python3.10/dist-packages/whisperx/transcribe.py\"\
          , line 195, in cli\r\n    result = align(result[\"segments\"], align_model,\
          \ align_metadata, input_audio, device, interpolate_method=interpolate_method,\
          \ return_char_alignments=return_char_alignments, print_progress=print_progress)\r\
          \n  File \"/usr/local/lib/python3.10/dist-packages/whisperx/alignment.py\"\
          , line 227, in align\r\n    trellis = get_trellis(emission, tokens, blank_id)\r\
          \n  File \"/usr/local/lib/python3.10/dist-packages/whisperx/alignment.py\"\
          , line 359, in get_trellis\r\n    trellis[t, 1:] + emission[t, blank_id],\r\
          \nIndexError: index 33 is out of bounds for dimension 1 with size 31\r\n\
          Execution time: 93.00095582008362 seconds\r\n\r\nBut, when I use your other\
          \ model (imvladikon/wav2vec2-xls-r-300m-lm-hebrew), I don't get the error.\
          \ \r\n\r\nHas there been some change that's causing the error?\r\n\r\nThanks\r\
          \n"
        updatedAt: '2023-10-05T20:03:24.511Z'
      numEdits: 0
      reactions: []
    id: 651f168ce3c8628055931a6b
    type: comment
  author: deedeeharris
  content: "Hey there.\r\nI've been using this model for Hebrew Diarization. It was\
    \ working fine. Recently I'm getting this error:\r\n\r\n2023-10-05 19:59:13.529821:\
    \ W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could\
    \ not find TensorRT\r\nLightning automatically upgraded your loaded checkpoint\
    \ from v1.5.4 to v2.0.9.post0. To apply the upgrade to your files permanently,\
    \ run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file ../root/.cache/torch/whisperx-vad-segmentation.bin`\r\
    \nModel was trained with pyannote.audio 0.0.1, yours is 3.0.0. Bad things might\
    \ happen unless you revert pyannote.audio to 0.x.\r\n>>Performing transcription...\r\
    \nDownloading (\u2026)rocessor_config.json: 100% 158/158 [00:00<00:00, 586kB/s]\r\
    \nDownloading (\u2026)okenizer_config.json: 100% 240/240 [00:00<00:00, 1.04MB/s]\r\
    \nDownloading (\u2026)lve/main/config.json: 100% 1.56k/1.56k [00:00<00:00, 6.70MB/s]\r\
    \nDownloading (\u2026)olve/main/vocab.json: 100% 304/304 [00:00<00:00, 1.88MB/s]\r\
    \nDownloading (\u2026)in/added_tokens.json: 100% 36.0/36.0 [00:00<00:00, 181kB/s]\r\
    \nDownloading (\u2026)cial_tokens_map.json: 100% 85.0/85.0 [00:00<00:00, 625kB/s]\r\
    \nSpecial tokens have been added in the vocabulary, make sure the associated word\
    \ embeddings are fine-tuned or trained.\r\nDownloading model.safetensors: 100%\
    \ 1.26G/1.26G [00:31<00:00, 39.5MB/s]\r\n>>Performing alignment...\r\nTraceback\
    \ (most recent call last):\r\n  File \"/usr/local/bin/whisperx\", line 8, in <module>\r\
    \n    sys.exit(cli())\r\n  File \"/usr/local/lib/python3.10/dist-packages/whisperx/transcribe.py\"\
    , line 195, in cli\r\n    result = align(result[\"segments\"], align_model, align_metadata,\
    \ input_audio, device, interpolate_method=interpolate_method, return_char_alignments=return_char_alignments,\
    \ print_progress=print_progress)\r\n  File \"/usr/local/lib/python3.10/dist-packages/whisperx/alignment.py\"\
    , line 227, in align\r\n    trellis = get_trellis(emission, tokens, blank_id)\r\
    \n  File \"/usr/local/lib/python3.10/dist-packages/whisperx/alignment.py\", line\
    \ 359, in get_trellis\r\n    trellis[t, 1:] + emission[t, blank_id],\r\nIndexError:\
    \ index 33 is out of bounds for dimension 1 with size 31\r\nExecution time: 93.00095582008362\
    \ seconds\r\n\r\nBut, when I use your other model (imvladikon/wav2vec2-xls-r-300m-lm-hebrew),\
    \ I don't get the error. \r\n\r\nHas there been some change that's causing the\
    \ error?\r\n\r\nThanks\r\n"
  created_at: 2023-10-05 19:03:24+00:00
  edited: false
  hidden: false
  id: 651f168ce3c8628055931a6b
  type: comment
is_pull_request: false
merge_commit_oid: null
num: 2
repo_id: imvladikon/wav2vec2-large-xlsr-53-hebrew
repo_type: model
status: open
target_branch: null
title: Recent Error
